### ISSUE TITLE
Strange layout behavior when size not explicitly set

### ISSUE THREAD

**Issue by arifu-dev** [taublast/DrawnUi.Maui#102]
I'm trying to understand if this is intended behavior with layout, so here's the code:
```    
    <draw:Canvas VerticalOptions="Fill" HorizontalOptions="Fill" WidthRequest="300" HeightRequest="300"> <draw:SkiaLayout Type="Column"  HorizontalOptions="Center" Margin="40" Spacing="25" BackgroundColor="Blue">
            <draw:SkiaLabel Text="Test" HorizontalOptions="Center" FontSize="28"/>
            <draw:SkiaShape VerticalOptions="Center" HorizontalOptions="Center" WidthRequest="100" HeightRequest="100" Type="Circle" BackgroundColor="Red"/>
        </draw:SkiaLayout>
    </draw:Canvas>
```

this results in the following:
![image](https://github.com/user-attachments/assets/5cb8f584-5c95-4867-8e05-0c3e7a50cf6a)

The SkiaLayout (blue) seems to size itself correctly, but the children within are positioned out of bounds
However once I set the WidthRequest=100 on the layout it looks like this:

![image](https://github.com/user-attachments/assets/e4b6a029-9291-48c5-a38c-62034f5e31ed)

The horizontal positioning is now correct and the blue area is now 162px in size and if I set HeightRequest=162

![image](https://github.com/user-attachments/assets/46d6d2f5-e931-48ee-bf8a-4e88562467cf)

It all fits correctly.
Is this intentional? Because it seems like the layout sizes itself correctly to fit the children, but does not take it's own size into account when positioning them.

**Comment by taublast** [comment]
Not at all. This all looks bugged as hell if you ask me. Just a huge thanks for bringing this out, on it.

**Comment by arifu-dev** [comment]
Looks more like it double centers, once against the canvas (green) and then adds the position offset from centering within the layout (blue):

![image](https://github.com/user-attachments/assets/922e232b-0fc4-4009-84f8-67f31fdb51ba)

**Comment by taublast** [comment]
Yep same as here, but i didn't got the idea initially https://github.com/taublast/DrawnUi.Maui/issues/94

Bugs inside `AdaptCachedLayout`, a hard one.

**Comment by arifu-dev** [comment]
Upon a second look today I realized that it's not actually doubling anything, rather it thinks that it can occupy all the remaining width and height of the canvas from the layout's position, instead of the measured layout:
![image](https://github.com/user-attachments/assets/a05a37bd-932c-4aca-8aa8-d49d2b6a3fb0)

I suspect that when measuring the children the parent passes width/height request rather than the measured size and since I didn't set anything it thinks it has all the available space. After a quick glance at the code I'd guess it's probably the values passed to `PostArrange` that are the issue rather than `AdaptCachedLayout`, but I'll test it out when I have the time unless you're able to figure something out first.

**Comment by taublast** [comment]
Thanks so much! I have found the reason and locations where the bug is happening. Would say it's a design issue. I'm currently thinking how to overcome this without reworking totally the layout system haha..

**Comment by arifu-dev** [comment]
So just a quick observation, maybe it can help you come up with a solution:
In the `SetMeasured` function if you lock in the WidthRequest and HeightRequest with the measured size like so:
```
if (WidthRequest == -1)
    WidthRequest = Width;
if (HeightRequest == -1)
    HeightRequest = Height;

MeasuredSize = ScaledSize.FromPixels(width, height, widthCut, heightCut, scale);
```

Then everything actually works correctly (at least in the example that was causing problems).
Perhaps a solution could be introducing variables `MeasuredWidth` and `MeasuredHeight`, replace the current usage of `WidthRequest ` and `HeightRequest` with the new variables and simply invalidate them when either the request variables change or when the layout changes.

**Comment by taublast** [comment]
Yeah that a quick cheat that works for this specific case and breaks other cases unfortunately :))
But this idea helps moving forward indeed, thanks so much for this.

**Comment by taublast** [comment]
Got a fix ready, now need to check other types of layout other that column/row and ill push to repo and nuget :)

**Comment by taublast** [comment]
Must be resolved with https://github.com/taublast/DrawnUi.Maui/pull/105/
