### ISSUE TITLE
Rotated shape is drawn without antialiasing

### ISSUE THREAD

**Issue by taublast** [taublast/DrawnUi.Maui#122]
### Discussed in https://github.com/taublast/DrawnUi.Maui/discussions/121

Nuget: version 1.2.5.2, Platform: WinUI.

<div type='discussions-op-text'>

<sup>Originally posted by **sferhah** November 13, 2024</sup>
Screenshot (top is with DrawnUi.Maui controls, bottom is with Maui controls)

<img width="314" alt="skia_vs_maui" src="https://github.com/user-attachments/assets/22c00d90-bf54-47a3-8c8a-1b29bb44346a">

Notice that there are no visibile pixels with the Maui Line control.

Here's my code:

```
    private static (SkiaShape, Point) CreateSkiaLine(Color color, double x1, double y1, double x2, double y2, int width = 5)
    {
        var distX = x1 - x2;
        var distY = y1 - y2;
        var lineDist = Math.Sqrt(distX * distX + distY * distY);

        var lineCenterX = x2 + (distX / 2);
        var lineCenterY = y2 + (distY / 2);
        var lineFinalX = lineCenterX - (lineDist / 2);

        var lineRotateAngle = Math.Acos(distX / lineDist) * (180 / Math.PI);

        var line = new SkiaShape()
        {            
            Type = ShapeType.Rectangle,
            BackgroundColor = color,
            WidthRequest = lineDist,
            HeightRequest = width,
            Rotation = (distY < 0) ? 360 - lineRotateAngle : lineRotateAngle
        };

        return (line, new Point(lineFinalX, lineCenterY));
    }
```</div>

**Comment by taublast** [comment]
Okay i would need a bit more code from your side here, here what I got:

![image](https://github.com/user-attachments/assets/d3309a7a-61b3-43d9-b61a-374f7cbb7012)

The line at the top is the one drawn with your code: it's a SkiaShape created with it, the stuff below was drawn on canvas manually to check how skia is antialiasing it overall. Was on Windows.

Again, I just failed to reproduce, could you help?

**Comment by sferhah** [comment]
Sorry for the late response, here it is:

<img width="358" alt="anti_aliasing" src="https://github.com/user-attachments/assets/f9033245-768e-481d-aa7b-304340695db8">

```
using DrawnUi.Maui.Views;
using Sandbox.Views;

namespace MauiNet8;

public partial class MainPageRepro : BasePage
{
    private SkiaLayout TreeLayout;
    public MainPageRepro()
    {
        this.Content = new Canvas
        {
            Gestures = GesturesMode.Enabled,
            HorizontalOptions = LayoutOptions.Fill,
            VerticalOptions = LayoutOptions.Fill,
            Content = TreeLayout = new SkiaLayout
            {
                HorizontalOptions = LayoutOptions.Fill,
                VerticalOptions = LayoutOptions.Fill,
                BackgroundColor = Colors.LightGray,
            }
        };

        foreach (Point node in new Point[]
        {
            new(150, 150),
            new(250,200),
            new(250,150),
            new(250,300),
            new(250,250),
            new(350,150),
            new(450,150),
            new(300,250),
            new(300,300),
            new(300,360),
            new(150,350)
        })
        {
            TreeLayout.Children.Add(CreateSkiaLine(Colors.Blue, 75, 175, node.X, node.Y));
        }
    }

    private static SkiaShape CreateSkiaLine(Color color, double x1, double y1, double x2, double y2, int width = 5)
    {
        var distX = x1 - x2;
        var distY = y1 - y2;
        var lineDist = Math.Sqrt(distX * distX + distY * distY);

        var lineCenterX = x2 + (distX / 2);
        var lineCenterY = y2 + (distY / 2);
        var lineFinalX = lineCenterX - (lineDist / 2);

        var lineRotateAngle = Math.Acos(distX / lineDist) * (180 / Math.PI);

        var line = new SkiaShape()
        {
            Type = ShapeType.Rectangle,
            BackgroundColor = color,
            WidthRequest = lineDist,
            HeightRequest = width,
            Rotation = (distY < 0) ? 360 - lineRotateAngle : lineRotateAngle,
            TranslationX = lineFinalX,
            TranslationY = lineCenterY,
        };

        return line;
    }
}
```

**Comment by taublast** [comment]
![image](https://github.com/user-attachments/assets/763a34dd-a6ef-4538-b816-6140cea7e500)
Looks like we fixed it :).  So grateful you revealed this bug it was affecting all the transformed rendering everywhere for all controls and I never noticed it! 
Will release a new nuget tomorrow.

**Comment by taublast** [comment]
i didnt use translation in my repro so it's sticked to 0,0. 
also just a friendly reminder you can heavily use UseCache="Operations" for your lines and blocks of lines so that when the canvas is redrawn it would just replay recorded operations from cache to re-create those lines without repeating calculations etc.

**Comment by sferhah** [comment]
Great, you're a genius!

**Comment by taublast** [comment]
Thanks, not at all!
Currently adding new types for skiashape Polygon and Line. They will use property `Points`. The main difference between them is Ply is a closed shape while Line can consist of any number of points not closing the shape. And supporting strokewidth obviously etc..
Why? For example, if one would rotate the shape it's considered transformed and when let's say one would apply shadows to it shadows will be rotated too. So for example with point I wouldn't use it, we need a separate type like polygon.  
Can think of using Line for example to show a path on a map..
If you have any suggestions on these new types, how you would like to see them etc, please share!

**Comment by taublast** [comment]
@sferhah Hey please check le nouveau nuget, pour `SkiaShape` j'ai ajouté `Line` (perfect for your project i guess) et puis ya le nouveau `Polygon` type, might also be very useful. N’hésite pas a critiquer stp, je m'en sers pas trop des shapes apart les `Rectangle`+`Circle`, alors.. :)

https://github.com/taublast/DrawnUi.Maui/discussions/134
