### ISSUE TITLE
App crashes at startup if SkiaFontManager does not find font

### ISSUE THREAD

**Issue by sferhah** [taublast/DrawnUi.Maui#124]
Suggested fix (SkiaFontManager line 32):

```
if (FileSystem.Current.AppPackageFileExistsAsync(file).GetAwaiter().GetResult()) // <- this is the "fix"
{
    using (Stream fileStream = FileSystem.Current.OpenAppPackageFileAsync(file).GetAwaiter().GetResult())
    {
        //
    }
}
```

How to reproduce:
Install "Syncfusion.Maui.DataGrid" Version="27.2.2" (it embeds a font named "MauiMaterialAssets") + ConfigureSyncfusionCore().
It will crash at .UseDrawnUi()

**Comment by taublast** [comment]
Hi the crash was like intended we should think about maybe how to find a compromise here. Maybe throw some kind of verbose exception. As this is all related to a developers set up the app should not continue silently if the developer has configured his app improperly.

**Comment by sferhah** [comment]
if the crash is intended then add:

```
if (!FileSystem.Current.AppPackageFileExistsAsync(file).GetAwaiter().GetResult())
{
    throw new ApplicationException($"Font declared but not found: {file}");
}
```
Because it crashes at FileSystem.Current.OpenAppPackageFileAsync(file) with an obscure message:

```
The system cannot find the file specified.

An item cannot be found with the specified name (UNABLE_TO_MASK_PATH).

```

**Comment by taublast** [comment]
Changed as 5bcd235147c523f548220e9362e982a621ae2f8f
