### ISSUE TITLE
Sandbox build failed: doesn't have a target for 'net8.0-windows10.0.19041.0'.

### ISSUE THREAD

**Issue by ToolmakerSteve** [taublast/DrawnUi.Maui#87]
Downloaded main branch (at 1.2.3.8 + 1 commit)

Two problems.

* Failed to restore D:\github\DrawnUi.Maui\src\samples\Sandbox\Sandbox.csproj (in 3 ms).
> NuGet package restore failed. Please see Error List window for detailed warnings and errors.

Error List:
> Unable to read project information for 'Sandbox': The property PackageVersion was expected to have a single value across all target frameworks, but instead had the following values: 1.0, 1.2.3.8

* Build succeeded for 8 projects; failed on Sandbox.

> 9>C:\Program Files\dotnet\sdk\8.0.303\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error NETSDK1005: Assets file 'D:\github\DrawnUi.Maui\src\samples\Sandbox\obj\project.assets.json' doesn't have a target for 'net8.0-windows10.0.19041.0'. Ensure that restore has run and that you have included 'net8.0-windows10.0.19041.0' in the TargetFrameworks for your project.
9>Done building project "Sandbox.csproj" -- FAILED.

**Comment by taublast** [comment]
Hey that looks like just an IDE problem to me.
Are you in VS?
Try to open the terminal where the sandbox project resides and do a `dotnet restore` for windows or `sudo dotnet restore` for mac.. This usually helps to manually restore projects and solutions when IDE gets messed up with its obsolete `obj`'s.

I'll add a github action meanwhile to build Sandbox for windows..

**Comment by ToolmakerSteve** [comment]
Thanks. I search for where `1.2.3.8` might be coming from. Looks like it is `Directory.Build.props` higher up in `src`. 

So Sandbox by itself would not have this issue.

I worked around it by adding PropertyGroup with PackageVersion 1.2.3.8 to Sandbox.csproj.  
Good enough for my purposes - now I can build & run sandbox and the drawnui engine all together. To see how it all works.

If I start over again at some point, I'll try `dotnet restore` at the sandbox project folder, as you suggest.

**Comment by taublast** [comment]
This all sounds very weird, this shouldn't normally require any workaround just a clean 'dotnet restore [name of solution]' from the folder where .sln files reside. Try restore manually?
