### ISSUE TITLE
sandbox deploy - app registration failed - splash screen image cannot be located

### ISSUE THREAD

**Issue by ToolmakerSteve** [taublast/DrawnUi.Maui#88]
DEP0700: Registration of the app failed. [0x80073CF6] AppxManifest.xml(34,27): error 0x80070002: Cannot install or update package 230e07b0-ebc2-4fde-9ac8-074d5c3269b3_9zz4h110yvjzm because the splash screen image [splashSplashScreen.png] cannot be located. Verify that the package contains an image that can be used as a splash screen for the application, and that the package manifest points to the correct location in the package where this splash screen image can be found.	Sandbox			

I'm just trying to launch Sandbox on windows under VS, as part of DrawnUI sln. I'll figure out how to skip this.

**Comment by taublast** [comment]
That's a known MAUI bug, unfortunately, happens randomly when the whole wasn't properly restored.

**Comment by ToolmakerSteve** [comment]
Ahh. Okay, good to know. I thought deleting bin and obj of Sandbox would be good enough.

FYI, after deleting all bin and objs from all projects, this time it successfully deployed.

I'll keep in mind to run "dotnet restore" if I run into this again.

**Comment by taublast** [comment]
Yeah there is a nice PS script for that to avoid manually searching for bin obj: https://github.com/taublast/DrawnUi.Maui/blob/main/src/DeleteBinObj.ps1
