### ISSUE TITLE
Sandbox / Carousels: MainPageCarousels / InitializeComponent: SkiaButton_Tapped signature

### ISSUE THREAD

**Issue by ToolmakerSteve** [taublast/DrawnUi.Maui#89]
> No method SkiaButton_Tapped with correct signature found on type Sandbox.Views.MainPageCarousels'

XAML:
```xaml
<draw:SkiaButton
  Tapped="SkiaButton_Tapped"
```
c#:
```cs
private void SkiaButton_Tapped(object sender, AppoMobi.Maui.Gestures.TouchActionEventArgs e)
```

-------------------------
Fix:
```cs
private void SkiaButton_Tapped(object sender, SkiaGesturesParameters e)
```

**Comment by taublast** [comment]
Has chaanged the signature indeed, might have not upgraded code in all the samples.. Thanks for pointing this out, will correct this one shortly. Meanwhile you could use the intellisense to correct to the correct signature if you want.

**Comment by ToolmakerSteve** [comment]
There is a similar line in MainPageDrawers, but the method is not currently called, so it doesn't complain.

**Comment by taublast** [comment]
Fix will get pushed soon.
